trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- checkout: self

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: './script.ps1'
    pwsh: true